pipeline:
  name: build-react-app
  identifier: build_react_app
  projectIdentifier: hello_harness_ci_pipeline
  orgIdentifier: default
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: VM
            spec:
              poolName: linux-amd64
  execution:
    steps:
      - step:
          type: Run
          name: Install Dependencies and Build
          identifier: install_and_build
        spec:
          shell: Sh
          command: |
            npm install
            npm run build
          image: node:18
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  properties:
    ci:
      codebase:
        connectorRef: account.GitHubjnayak1482
        repoName: hello-harness
        build:
          type: branch
          spec:
            branch: main # Changed for stability
  delegateSelectors:
    - linux-amd64 # Ensures correct delegate selection
  variables:
    - name: RUNNER_HOST
      type: String
      value: "192.168.1.44" # Change to actual runner IP
    - name: RUNNER_PORT
      type: Number
      value: 3000